In [ ]:
#basic lib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#Sub-stage 1.2: Import Deep Learning Libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [ ]:
from sklearn.model_selection import train_test_split
from math import sqrt
from sklearn.metrics import mean_squared_error,r2_score, mean_absolute_error

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional
import matplotlib.pyplot as plt

In [ ]:
!wget https://www.dropbox.com/s/wa8d1sujzlx56hh/ETL_DATA_new.csv

--2024-07-18 13:58:01--  https://www.dropbox.com/s/wa8d1sujzlx56hh/ETL_DATA_new.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.18, 2620:100:6016:18::a27d:112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.dropbox.com/scl/fi/xfqhfaqam1mbvmlapv5z1/ETL_DATA_new.csv?rlkey=fcox2uze73hrreid6e78nvufg [following]
--2024-07-18 13:58:01--  https://www.dropbox.com/scl/fi/xfqhfaqam1mbvmlapv5z1/ETL_DATA_new.csv?rlkey=fcox2uze73hrreid6e78nvufg
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucec5a7171087a99bd5cfe537816.dl.dropboxusercontent.com/cd/0/inline/CW9hN1Iwe-cnNSosib0c3KyPzFO-mC8dIE8rYUNIakAryU-9eOO-D5NiGBTJtJxnrgEg1PKC-H40boSxEtas5WdHSP4QheTln28gT2Vw9S9GxLThfBUaOP_rAzvkvr2lQw6dtbOvg1upJOP-I4yW7tMc/file# [following]
--2024-07-18 13:58:02--  https://ucec5a7171087a99bd5cfe537816.dl.dropboxusercontent.com/cd/0/inline/CW9hN1Iwe-cnNSosib0c3KyPzFO-mC8dIE8rYUNIakAryU-9eOO-D5NiGBTJtJxnrgEg1PKC-H40boSxEtas5WdHSP4QheTln28gT2Vw9S9GxLThfBUaOP_rAzvkvr2lQw6dtbOvg1upJOP-I4yW7tMc/file
Resolving ucec5a7171087a99bd5cfe537816.dl.dropboxusercontent.com (ucec5a7171087a99bd5cfe537816.dl.dropboxusercontent.com)... 162.125.1.15, 2620:100:6016:15::a27d:10f
Connecting to ucec5a7171087a99bd5cfe537816.dl.dropboxusercontent.com (ucec5a7171087a99bd5cfe537816.dl.dropboxusercontent.com)|162.125.1.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 262918270 (251M) [text/plain]
Saving to: ‘ETL_DATA_new.csv’

ETL_DATA_new.csv    100%[===================>] 250.74M  60.4MB/s    in 4.6s

2024-07-18 13:58:07 (54.5 MB/s) - ‘ETL_DATA_new.csv’ saved [262918270/262918270]

In [ ]:
import pandas as pd
df=pd.read_csv('ETL_DATA_new.csv')
df.head(10)

,,TimeStamp,Point(139.0794379 36.3727776),Point(139.1051411 36.3963822),Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3526243 36.3695416),Point(139.1945766 36.31351160000001),...,Point(139.9418164 36.7656467),Point(140.0549894 36.9688923),Point(139.8775674 36.3847082),Point(139.9101767 36.4393022),Point(139.9074816 36.4445767),Point(140.0934838 36.4673588),Point(139.7422865 36.2305774),Point(139.7151723 36.822353),Point(140.1510903 36.6598314),Unnamed: 1832
0,0,2018-01-01 01:00:00,NaN,NaN,5.0,13.0,18.0,20.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,4.0,NaN
1,1,2018-01-01 02:00:00,NaN,NaN,11.0,12.0,22.0,15.0,NaN,NaN,...,NaN,6.0,NaN,NaN,NaN,9.0,NaN,NaN,5.0,NaN
2,2,2018-01-01 03:00:00,NaN,NaN,7.0,12.0,19.0,16.0,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,10.0,NaN,NaN,6.0,NaN
3,3,2018-01-01 04:00:00,NaN,NaN,5.0,11.0,16.0,11.0,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,11.0,NaN,NaN,11.0,NaN
4,4,2018-01-01 05:00:00,NaN,NaN,6.0,11.0,10.0,8.0,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,8.0,NaN,NaN,6.0,NaN
5,5,2018-01-01 06:00:00,NaN,NaN,5.0,11.0,11.0,11.0,NaN,NaN,...,NaN,-3.0,NaN,NaN,NaN,9.0,NaN,NaN,3.0,NaN
6,6,2018-01-01 07:00:00,NaN,NaN,3.0,10.0,15.0,11.0,NaN,NaN,...,NaN,-1.0,NaN,NaN,NaN,6.0,NaN,NaN,9.0,NaN
7,7,2018-01-01 08:00:00,NaN,NaN,4.0,10.0,10.0,9.0,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,13.0,NaN,NaN,2.0,NaN
8,8,2018-01-01 09:00:00,NaN,NaN,-2.0,10.0,-21.0,13.0,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,15.0,NaN,NaN,4.0,NaN
9,9,2018-01-01 10:00:00,NaN,NaN,1.0,9.0,-50.0,12.0,NaN,NaN,...,NaN,5.0,NaN,NaN,NaN,11.0,NaN,NaN,4.0,NaN

In [ ]:
# timestamp column as index
dataset = df.set_index('TimeStamp')
dataset

,,Point(139.0794379 36.3727776),Point(139.1051411 36.3963822),Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3526243 36.3695416),Point(139.1945766 36.31351160000001),Point(139.2076974 36.3034767),...,Point(139.9418164 36.7656467),Point(140.0549894 36.9688923),Point(139.8775674 36.3847082),Point(139.9101767 36.4393022),Point(139.9074816 36.4445767),Point(140.0934838 36.4673588),Point(139.7422865 36.2305774),Point(139.7151723 36.822353),Point(140.1510903 36.6598314),Unnamed: 1832
TimeStamp,,,,,,,,,,,,,,,,,,,,,
2018-01-01 01:00:00,0,NaN,NaN,5.0,13.0,18.0,20.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,4.0,NaN
2018-01-01 02:00:00,1,NaN,NaN,11.0,12.0,22.0,15.0,NaN,NaN,NaN,...,NaN,6.0,NaN,NaN,NaN,9.0,NaN,NaN,5.0,NaN
2018-01-01 03:00:00,2,NaN,NaN,7.0,12.0,19.0,16.0,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,10.0,NaN,NaN,6.0,NaN
2018-01-01 04:00:00,3,NaN,NaN,5.0,11.0,16.0,11.0,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,11.0,NaN,NaN,11.0,NaN
2018-01-01 05:00:00,4,NaN,NaN,6.0,11.0,10.0,8.0,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,8.0,NaN,NaN,6.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-25 18:00:00,46000,NaN,NaN,NaN,22.0,3.0,15.0,NaN,NaN,NaN,...,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN
2023-04-25 19:00:00,46001,NaN,NaN,NaN,21.0,2.0,19.0,NaN,NaN,NaN,...,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN
2023-04-25 20:00:00,46002,NaN,NaN,NaN,20.0,10.0,19.0,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN
2023-04-25 21:00:00,46003,NaN,NaN,NaN,19.0,2.0,15.0,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN
2023-04-25 22:00:00,46004,NaN,NaN,NaN,19.0,1.0,17.0,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN

In [ ]:
threshold = 0.3 * len(df)
df = df.dropna(thresh=threshold, axis=1)
df.head(10)

,,TimeStamp,Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3817322 36.2909131),Point(139.0432674 36.64710669999999),Point(139.5317782 36.2499123),Point(138.8939601 36.25898610000001),...,Point(139.5820566 36.330908),Point(139.745005 36.5669749),Point(139.6800109 36.7257039),Point(139.8002801 36.313294),Point(140.0136724 36.4403673),Point(140.0155171 36.8708174),Point(139.9239959 36.8062129),Point(140.0549894 36.9688923),Point(140.0934838 36.4673588),Point(140.1510903 36.6598314)
0,0,2018-01-01 01:00:00,5.0,13.0,18.0,20.0,23.0,14.0,26.0,4.0,...,14.0,2.0,1.0,17.0,11.0,8.0,1.0,NaN,6.0,4.0
1,1,2018-01-01 02:00:00,11.0,12.0,22.0,15.0,32.0,16.0,26.0,2.0,...,19.0,1.0,5.0,23.0,16.0,6.0,0.0,6.0,9.0,5.0
2,2,2018-01-01 03:00:00,7.0,12.0,19.0,16.0,32.0,16.0,21.0,2.0,...,17.0,8.0,1.0,23.0,11.0,3.0,2.0,0.0,10.0,6.0
3,3,2018-01-01 04:00:00,5.0,11.0,16.0,11.0,28.0,6.0,24.0,5.0,...,14.0,5.0,1.0,24.0,11.0,4.0,3.0,2.0,11.0,11.0
4,4,2018-01-01 05:00:00,6.0,11.0,10.0,8.0,27.0,9.0,22.0,8.0,...,13.0,-3.0,4.0,18.0,17.0,3.0,5.0,4.0,8.0,6.0
5,5,2018-01-01 06:00:00,5.0,11.0,11.0,11.0,24.0,7.0,21.0,3.0,...,9.0,4.0,5.0,9.0,9.0,2.0,4.0,-3.0,9.0,3.0
6,6,2018-01-01 07:00:00,3.0,10.0,15.0,11.0,21.0,10.0,22.0,0.0,...,9.0,6.0,0.0,11.0,18.0,5.0,5.0,-1.0,6.0,9.0
7,7,2018-01-01 08:00:00,4.0,10.0,10.0,9.0,21.0,9.0,22.0,0.0,...,12.0,7.0,6.0,11.0,13.0,5.0,2.0,4.0,13.0,2.0
8,8,2018-01-01 09:00:00,-2.0,10.0,-21.0,13.0,14.0,-4.0,19.0,4.0,...,10.0,4.0,6.0,19.0,16.0,1.0,7.0,2.0,15.0,4.0
9,9,2018-01-01 10:00:00,1.0,9.0,-50.0,12.0,1.0,-10.0,15.0,0.0,...,19.0,5.0,-1.0,20.0,11.0,3.0,5.0,5.0,11.0,4.0

In [ ]:
 # Replace NaN values with 0
dataset0= df.fillna(0)

In [ ]:
 # Drop the 'TimeStamp' column if it's still present
if 'TimeStamp' in dataset0.columns:
    dataset0 = dataset0.drop('TimeStamp', axis=1)

# Now calculate the moving average
dataset0_moving_average = dataset0.rolling(window=2).mean()  # Adjust window size as needed
dataset0_moving_average

,,Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3817322 36.2909131),Point(139.0432674 36.64710669999999),Point(139.5317782 36.2499123),Point(138.8939601 36.25898610000001),Point(138.8275195 36.5786787),...,Point(139.5820566 36.330908),Point(139.745005 36.5669749),Point(139.6800109 36.7257039),Point(139.8002801 36.313294),Point(140.0136724 36.4403673),Point(140.0155171 36.8708174),Point(139.9239959 36.8062129),Point(140.0549894 36.9688923),Point(140.0934838 36.4673588),Point(140.1510903 36.6598314)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.5,8.0,12.5,20.0,17.5,27.5,15.0,26.0,3.0,3.5,...,16.5,1.5,3.0,20.0,13.5,7.0,0.5,3.0,7.5,4.5
2,1.5,9.0,12.0,20.5,15.5,32.0,16.0,23.5,2.0,2.5,...,18.0,4.5,3.0,23.0,13.5,4.5,1.0,3.0,9.5,5.5
3,2.5,6.0,11.5,17.5,13.5,30.0,11.0,22.5,3.5,1.0,...,15.5,6.5,1.0,23.5,11.0,3.5,2.5,1.0,10.5,8.5
4,3.5,5.5,11.0,13.0,9.5,27.5,7.5,23.0,6.5,5.0,...,13.5,1.0,2.5,21.0,14.0,3.5,4.0,3.0,9.5,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46000,45999.5,0.0,22.0,9.5,18.0,15.0,15.5,12.5,12.0,14.0,...,12.0,8.0,10.5,12.5,10.0,0.0,12.0,7.0,0.0,9.0
46001,46000.5,0.0,21.5,2.5,17.0,15.0,15.5,12.5,11.0,14.0,...,10.5,11.5,11.0,11.5,9.5,0.0,11.5,6.0,0.0,9.0
46002,46001.5,0.0,20.5,6.0,19.0,13.5,14.0,12.0,10.5,13.0,...,9.0,14.0,10.5,11.0,8.0,0.0,11.0,4.5,0.0,8.5
46003,46002.5,0.0,19.5,6.0,17.0,11.5,14.0,12.5,9.5,13.0,...,12.5,10.0,9.0,11.5,8.5,0.0,10.5,4.0,0.0,9.0
46004,46003.5,0.0,19.0,1.5,16.0,11.5,14.0,12.5,9.5,14.0,...,14.0,10.5,10.5,13.0,10.5,0.0,9.5,4.0,0.0,9.5

In [ ]:
df1=dataset0_moving_average.iloc[:,:10]
df1.head(10)

,,Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3817322 36.2909131),Point(139.0432674 36.64710669999999),Point(139.5317782 36.2499123),Point(138.8939601 36.25898610000001),Point(138.8275195 36.5786787)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.5,8.0,12.5,20.0,17.5,27.5,15.0,26.0,3.0,3.5
2,1.5,9.0,12.0,20.5,15.5,32.0,16.0,23.5,2.0,2.5
3,2.5,6.0,11.5,17.5,13.5,30.0,11.0,22.5,3.5,1.0
4,3.5,5.5,11.0,13.0,9.5,27.5,7.5,23.0,6.5,5.0
5,4.5,5.5,11.0,10.5,9.5,25.5,8.0,21.5,5.5,7.5
6,5.5,4.0,10.5,13.0,11.0,22.5,8.5,21.5,1.5,4.5
7,6.5,3.5,10.0,12.5,10.0,21.0,9.5,22.0,0.0,3.0
8,7.5,1.0,10.0,-5.5,11.0,17.5,2.5,20.5,2.0,1.0
9,8.5,-0.5,9.5,-35.5,12.5,7.5,-7.0,17.0,2.0,1.5

In [ ]:
# Normilization
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df2= pd.DataFrame(scaler.fit_transform(df1), columns=df1.columns)
df2

,,Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3817322 36.2909131),Point(139.0432674 36.64710669999999),Point(139.5317782 36.2499123),Point(138.8939601 36.25898610000001),Point(138.8275195 36.5786787)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000000,0.534884,0.201299,0.455526,0.435583,0.419463,0.386266,0.430769,0.427481,0.104167
2,0.000022,0.541528,0.194805,0.458221,0.411043,0.449664,0.394850,0.392308,0.423664,0.098214
3,0.000043,0.521595,0.188312,0.442049,0.386503,0.436242,0.351931,0.376923,0.429389,0.089286
4,0.000065,0.518272,0.181818,0.417790,0.337423,0.419463,0.321888,0.384615,0.440840,0.113095
...,...,...,...,...,...,...,...,...,...,...
46000,0.999913,0.481728,0.324675,0.398922,0.441718,0.335570,0.390558,0.223077,0.461832,0.166667
46001,0.999935,0.481728,0.318182,0.361186,0.429448,0.335570,0.390558,0.223077,0.458015,0.166667
46002,0.999957,0.481728,0.305195,0.380054,0.453988,0.325503,0.377682,0.215385,0.456107,0.160714
46003,0.999978,0.481728,0.292208,0.380054,0.429448,0.312081,0.377682,0.223077,0.452290,0.160714
46004,1.000000,0.481728,0.285714,0.355795,0.417178,0.312081,0.377682,0.223077,0.452290,0.166667

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Bidirectional, LSTM, Dense
from tensorflow.keras.optimizers import Adam

# Function to create and compile a BiLSTM model
def create_bilstm_model(input_shape):
    model = Sequential()
    model.add(Bidirectional(LSTM(64, input_shape=(input_shape[1], input_shape[2]))))
    model.add(Dense(1))
    model.compile(optimizer=Adam(learning_rate=0.001), loss='mean_squared_error')
    return model

# Sample Data Loading (Replace with your actual dataset)
df2

# Metrics storage
performance_metrics = []

# Iterate through each column as the target
for column in df2.columns:
    # Prepare data
    X = df2.drop(column, axis=1).values
    y = df2[column].values

    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Scale the features
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Reshape for BiLSTM (needs an additional channel dimension)
    X_train_rnn = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
    X_test_rnn = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

    # Create and train the BiLSTM model
    model = create_bilstm_model(X_train_rnn.shape)
    model.fit(X_train_rnn, y_train, epochs=10, batch_size=32, verbose=0)
    predictions = model.predict(X_test_rnn).flatten()

    # Check and handle NaNs in predictions
    if np.isnan(predictions).any():
        print(f"Warning: NaN predictions encountered for column {column}. Replacing NaNs with 0.")
        predictions = np.nan_to_num(predictions, nan=0.0)  # Replace NaNs with 0

    # Calculate metrics
    mse = mean_squared_error(y_test, predictions)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, predictions)
    mae = mean_absolute_error(y_test, predictions)

    # Store metrics
    performance_metrics.append({'Column': column, 'MSE': mse, 'RMSE': rmse, 'R2': r2, 'MAE': mae})

# Convert performance metrics to DataFrame
performance_df = pd.DataFrame(performance_metrics)

# Print the performance table
print("Performance of BiLSTM Model:")
print(performance_df)

288/288 [==============================] - 3s 6ms/step
Warning: NaN predictions encountered for column  . Replacing NaNs with 0.
288/288 [==============================] - 2s 5ms/step
Warning: NaN predictions encountered for column Point(139.0960211 36.4047323). Replacing NaNs with 0.
288/288 [==============================] - 2s 5ms/step
Warning: NaN predictions encountered for column Point(139.0428727 36.3816035). Replacing NaNs with 0.
288/288 [==============================] - 2s 5ms/step
Warning: NaN predictions encountered for column Point(138.9955116 36.33801589999999). Replacing NaNs with 0.
288/288 [==============================] - 2s 5ms/step
Warning: NaN predictions encountered for column Point(139.342672 36.4105658). Replacing NaNs with 0.
288/288 [==============================] - 3s 6ms/step
Warning: NaN predictions encountered for column Point(139.3817322 36.2909131). Replacing NaNs with 0.
288/288 [==============================] - 2s 4ms/step
Warning: NaN predictions encountered for column Point(139.0432674 36.64710669999999). Replacing NaNs with 0.
288/288 [==============================] - 4s 6ms/step
Warning: NaN predictions encountered for column Point(139.5317782 36.2499123). Replacing NaNs with 0.
288/288 [==============================] - 3s 7ms/step
Warning: NaN predictions encountered for column Point(138.8939601 36.25898610000001). Replacing NaNs with 0.
288/288 [==============================] - 2s 5ms/step
Warning: NaN predictions encountered for column Point(138.8275195 36.5786787). Replacing NaNs with 0.
Performance of BiLSTM Model:
                                 Column       MSE      RMSE          R2  \
0                                        0.331268  0.575559   -2.957885
1         Point(139.0960211 36.4047323)  0.283960  0.532879 -106.654546
2         Point(139.0428727 36.3816035)  0.033654  0.183450   -3.008050
3  Point(138.9955116 36.33801589999999)  0.162750  0.403422  -35.688750
4          Point(139.342672 36.4105658)  0.132889  0.364539  -15.511283
5         Point(139.3817322 36.2909131)  0.092169  0.303594  -30.652828
6  Point(139.0432674 36.64710669999999)  0.113965  0.337586  -20.123047
7         Point(139.5317782 36.2499123)  0.054079  0.232550   -3.521437
8  Point(138.8939601 36.25898610000001)  0.196863  0.443693 -307.700866
9         Point(138.8275195 36.5786787)  0.017709  0.133073   -8.879991

        MAE
0  0.497564
1  0.530398
2  0.158925
3  0.397887
4  0.353328
5  0.298760
6  0.329499
7  0.205229
8  0.442973
9  0.126159